### ISSUE TITLE
Make the code a pip installable package

### ISSUE THREAD

**Issue by oni-on** [oni-on/item-collaborative-filtering#4]
- add class docstring (following sklearn convention)

**Comment by oni-on** [comment]
@fbarl what do you think of the package names `itemrec` or `item_cf` (stands for collaborative filtering)?

According to this [guide](https://www.python.org/dev/peps/pep-0008/#package-and-module-names):
> Python packages should also have short, all-lowercase names, although the use of underscores is discouraged.

**Comment by fbarl** [comment]
I don't really know what to say, seems like a tough one :) `itemrec` sounds too generic, `item_cf` is good if the _item_ part is more relevant than _collaborative filtering_.

Some other ideas: `amazon_icf`, `icf_recommender`, `item_collaborative_filtering`, `item2item`

I don't think the name you choose will be as important as the tags you decide to use e.g. on Github, so I wouldn't waste too much time on this decision.

**Comment by oni-on** [comment]
Thanks @fbarl ! In the end I'll go with `icf_recommender` because I think it's a good idea to have the word recommender in there
