### ISSUE TITLE
Refactor to speed up computations 

### ISSUE THREAD

**Issue by oni-on** [oni-on/item-collaborative-filtering#7]
- __count_users_interactions(self, df, item):
Interactions SHOULD be computed just once per user, not x many times where x = number of items that the user interacted with
- __item_interaction_probability(self, df, item):
probability should be computed just once per item, not y many times where y = number of item pairs the item appears in
- __count_common_item_pair_users(self, df, item_pair):
is now computed unnecessarily twice. the result is the same for item pairs (x, y) and (y, x)

**Comment by oni-on** [comment]
Possible implementation: one function computes interactions for all users, and another just looks them up for the users of an item

**Comment by fbarl** [comment]
Related to #6.
